name: Anvil
version: '${project.version}'
main: org.vestingdart.anvil.Main
api-version: '1.20'
commands:
  anvil:
    description: "Opens the Anvil"
    aliases:
      - ambos
    permission: galaxicraft.multi.anvil
    permission-message: "Galaxicraft ---> You dont have permission for executing this command"
  workbench:
    description: "Opens the Workbench"
    aliases:
      - wb
      - craft
    permission: galaxicraft.mulit.workbench
    permission-message: "Galaxicraft ---> You dont have permission for executing this command"
  smithingtable:
    description: "Opens the Smithing Table"
    aliases:
      - schmiedetisch
    permission: galaxicraft.mulit.smithingtable
    permission-message: "Galaxicraft ---> You dont have permission for executting this command"